import Layout from "@/components/Layout";
import SEOHead from "@/components/SEOHead";
import { Link } from "react-router-dom";
import { Search, ArrowRight, Hash, Info, HelpCircle } from "lucide-react";
import InternalLinkingHub from "@/components/InternalLinkingHub";
import { AdSlot } from "@/components/ads/AdSlot";

const TrackingNumberFormatsPage = () => {
  // ❌ FAQPage schema removed - not eligible for commercial sites (Google policy Aug 2023)

  return (
    <Layout>
      <SEOHead
        title="USPS Tracking Number Formats – 9200, 9205, 9214, 9261 Explained"
        description="Understand USPS tracking number formats. Learn what 9200, 9205, 9214, 9261, 9270, 9300, 9400 prefixes mean. How many digits in a USPS tracking number? Complete guide to USPS tracking number formats."
        canonical="/tracking-number-formats"
        keywords="9200 tracking number usps, 9205 usps tracking, 9214 usps tracking, 9261 usps tracking, usps tracking number format, how many digits in usps tracking number, usps tracking number, what does a usps tracking number look like, usps tracking number starts with, usps tracking number length, usps tracking number digits, how many numbers in a usps tracking number, how long is a usps tracking number"
        structuredData={faqSchema}
      />

      <section className="bg-gradient-to-br from-primary via-primary/90 to-primary/80 text-primary-foreground py-16">
        <div className="container max-w-4xl text-center">
          <div className="inline-flex items-center gap-2 bg-accent/10 border border-accent/20 rounded-full px-4 py-2 mb-6">
            <Hash className="h-4 w-4 text-accent" />
            <span className="text-xs font-semibold text-accent uppercase tracking-wide">Tracking Number Guide</span>
          </div>
          <h1 className="text-4xl md:text-5xl lg:text-6xl font-black mb-4 tracking-tight">USPS Tracking Number Formats</h1>
          <p className="text-lg text-primary-foreground/70 max-w-2xl mx-auto mb-8">
            Complete guide to USPS tracking number formats. Understand what 9200, 9205, 9214, 9261, and other prefixes mean. Learn how to identify your USPS service by tracking number.
          </p>
          <Link to="/" className="inline-flex items-center gap-2 bg-accent text-accent-foreground px-8 py-4 rounded-xl font-bold text-lg hover:bg-accent/90 transition-colors">
            <Search className="h-5 w-5" /> Track Your Number <ArrowRight className="h-5 w-5" />
          </Link>
        </div>
      </section>

      <section className="container max-w-4xl py-12">
        <h2 className="text-2xl font-bold text-foreground mb-4">Understanding USPS Tracking Number Formats</h2>
        <div className="prose prose-sm max-w-none text-muted-foreground space-y-4 leading-relaxed">
          <p>
            Every <strong>USPS tracking number</strong> contains coded information about the shipping service, origin, and package type. Understanding these formats helps you identify what service was used, expected delivery times, and troubleshoot tracking issues. The most common question is "<strong>how many digits in a USPS tracking number?</strong>" — domestic numbers are 20-22 digits, while international numbers are 13 characters.
          </p>
          <p>
            USPS uses a standardized numbering system where the first 4 digits (the <strong>prefix</strong>) identify the shipping service. For example, <strong>9200</strong> indicates Ground Advantage/First-Class Package, <strong>9205</strong> indicates Priority Mail, and <strong>9270</strong> indicates Priority Mail Express. By understanding these prefixes, you can instantly know what service level to expect.
          </p>
        </div>
      </section>

      <section className="bg-muted py-12">
        <div className="container max-w-4xl">
          <h2 className="text-2xl font-bold text-foreground mb-6">Domestic Tracking Number Prefixes</h2>
          <div className="space-y-3">
            {[
              { prefix: "9200", service: "First-Class Package / Ground Advantage", digits: "20-22", delivery: "2-5 business days", example: "9200 1901 0083 0049 0000 17", desc: "Most common prefix for affordable package shipping." },
              { prefix: "9205", service: "Priority Mail", digits: "20-22", delivery: "1-3 business days", example: "9205 5901 6175 5752 7715 88", desc: "USPS's most popular expedited service." },
              { prefix: "9214", service: "Priority Mail / Click-N-Ship", digits: "22", delivery: "1-3 business days", example: "9214 8901 0000 0000 0000 00", desc: "Generated by USPS.com and shipping platforms." },
              { prefix: "9261", service: "Presorted / Commercial", digits: "20-22", delivery: "2-5 business days", example: "9261 2901 0000 0000 0000 00", desc: "Used by businesses and e-commerce." },
              { prefix: "9270", service: "Priority Mail Express", digits: "20-22", delivery: "Overnight-2 days", example: "9270 1901 0083 0049 0000 17", desc: "Fastest USPS service with money-back guarantee." },
              { prefix: "9300", service: "USPS Retail Ground", digits: "20-22", delivery: "2-8 business days", example: "9300 1201 1140 5209 3546 00", desc: "Legacy service, now replaced by Ground Advantage." },
              { prefix: "9361", service: "USPS Marketing Mail", digits: "22", delivery: "3-10 business days", example: "9361 2896 0000 0000 0000 00", desc: "Bulk commercial mail with limited tracking." },
              { prefix: "9400", service: "Ground Advantage / First-Class", digits: "20-22", delivery: "2-5 business days", example: "9400 1118 9922 3033 0052 82", desc: "Alternative prefix for package services." },
              { prefix: "9407", service: "Certified Mail", digits: "20", delivery: "3-5 business days", example: "9407 1118 9922 3397 7194 00", desc: "Certified mail with signature and proof of mailing." },
              { prefix: "9410", service: "Registered Mail", digits: "20-22", delivery: "10-14 business days", example: "9410 8036 0000 0000 0000 00", desc: "Maximum security mail with chain-of-custody." },
            ].map((item) => (
              <div key={item.prefix} className="bg-card border rounded-lg p-4">
                <div className="flex items-center justify-between mb-2">
                  <h3 className="font-bold text-foreground font-mono text-lg">{item.prefix}</h3>
                  <span className="text-xs font-semibold text-primary bg-primary/10 px-2 py-1 rounded">{item.delivery}</span>
                </div>
                <p className="font-semibold text-sm text-foreground">{item.service}</p>
                <p className="text-xs text-muted-foreground mt-1">{item.desc}</p>
                <p className="text-xs font-mono text-muted-foreground/70 mt-1">Example: {item.example}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="container max-w-4xl py-12">
        <h2 className="text-2xl font-bold text-foreground mb-6">International Tracking Number Formats</h2>
        <div className="overflow-x-auto">
          <table className="w-full text-sm border-collapse">
            <thead>
              <tr className="bg-muted">
                <th className="text-left p-3 border font-bold text-foreground">Prefix</th>
                <th className="text-left p-3 border font-bold text-foreground">Service</th>
                <th className="text-left p-3 border font-bold text-foreground">Format</th>
                <th className="text-left p-3 border font-bold text-foreground">Example</th>
              </tr>
            </thead>
            <tbody className="text-muted-foreground">
              {[
                ["EA, EB, EC", "Priority Mail Express Int'l", "13 chars", "EA123456789US"],
                ["CP, CX", "Priority Mail International", "13 chars", "CP123456789US"],
                ["LA, LB, LC", "First-Class Package Int'l", "13 chars", "LA123456789US"],
                ["RA, RB, RC", "Registered Mail Int'l", "13 chars", "RA123456789US"],
                ["UD, UE", "Global Express Guaranteed", "13 chars", "UD123456789US"],
              ].map(([prefix, service, format, example]) => (
                <tr key={prefix}>
                  <td className="p-3 border font-mono font-bold">{prefix}</td>
                  <td className="p-3 border">{service}</td>
                  <td className="p-3 border">{format}</td>
                  <td className="p-3 border font-mono">{example}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      <section className="container max-w-4xl py-12">
        <h2 className="text-2xl font-bold text-foreground mb-4">Related Tracking Tools</h2>
        <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
          {[
            { label: "USPS Tracking", to: "/" },
            { label: "Priority Mail Tracking", to: "/priority-mail-tracking" },
            { label: "Certified Mail Tracking", to: "/certified-mail-tracking" },
            { label: "Express Mail Tracking", to: "/express-mail-tracking" },
            { label: "Ground Advantage Tracking", to: "/ground-advantage-tracking" },
            { label: "First Class Tracking", to: "/first-class-tracking" },
            { label: "International Tracking", to: "/international-tracking" },
            { label: "Tracking Lookup", to: "/tracking-lookup" },
            { label: "Track USPS", to: "/track-usps" },
          ].map((link) => (
            <Link key={link.to} to={link.to} className="text-sm text-primary hover:underline bg-card border rounded-lg p-3 text-center">
              {link.label}
            </Link>
          ))}
        </div>
      </section>

      <div className="container py-3 flex justify-center"><AdSlot slotId="content-ad" /></div>
      <InternalLinkingHub />
    </Layout>
  );
};

export default TrackingNumberFormatsPage;
